global using Microsoft.Extensions.Configuration;
global using Newtonsoft.Json;
global using System;
global using System.IO;
global using System.Net.Http;
global using System.Text;
global using System.Threading.Tasks;
global using wetterclient.Data;
global using wetterclient.Ausgabe;
global using wetterclient.Data.Astro;
global using System.Speech.Synthesis;
namespace wetterclient;